### ISSUE TITLE
possible to add a "cmd" variable to each type of monster?

### ISSUE THREAD

**Issue by L3thalBunny** [rkubik/RaidBoss#15]
If we could have add something like:

cmd:
 - /randomArmor [monster]

that runs a command that targets the monster; I could make a command that gives the monster a random "kit" with different items. Essentials kit's drops the items on the ground if the player inventory is full or inaccessible (i think) so it would imitate the monster dropping the items on death, allowing us MUCH more freedom in terms of what we want monsters to drop

**Comment by rkubik** [comment]
Fixed in v2. 

```
commands:
  spawn:
    - say Raid Boss [monster] spawned!
  death:
    - summon Item ~ ~ ~ [monsterx] [monstery] [monsterz]
   kill:
     - summon item ~ ~ ~ [monsterx] [monstery] [monsterz]
```
